"""update contacts(made first_name not unique)

Revision ID: b786f0665dc2
Revises: cbbcd881e672
Create Date: 2026-04-27 20:17:38.841950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b786f0665dc2'
down_revision: Union[str, Sequence[str], None] = 'cbbcd881e672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('contacts_first_name_key'), 'contacts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('contacts_first_name_key'), 'contacts', ['first_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
